### ISSUE TITLE
Support for BigEndian architectures

### ISSUE THREAD

**Issue by JustAMan** [Bond-009/ImageSize.Net#1]
The code here
https://github.com/Bond-009/ImageSize.Net/blob/4b10500659da1b5798ff9e0f6b7785f49fdd0f25/src/ImageSize.Net/Image.cs#L215
seems to assume it runs on LittleEndian, which might not be the case.
Why don't you just use builtin utilities to convert from "network byte order" which is guaranteed to be BigEndian to "host order"?

**Comment by JustAMan** [comment]
Typical example might be ARM which according to Wikipedia can run both in BigEndian and LittleEndian.

**Comment by Bond-009** [comment]
This *should* work on Big Endian systems.
BinaryReader always reads in Little Endian, and my BigEndian extension should work the same on Big Endian systems.
But we can be 100% until we test it.
